GET http://localhost:3000/pesquisas

###

GET http://localhost:3000/pesquisas/MercadoLivre

###

GET http://localhost:3000/pesquisas/605d39ffd649ec48ec9d3bbf

###

POST http://localhost:3000/pesquisas/q=arduino
Content-Type: application/json

{
    "pesquisaFiltro": "q=raspberry",
        "thumbnail": "req.body.resultados.thumbnail",
        "title": "req.body.resultados.title",
        "address_city_name": "req.body.resultados.address_city_name",
        "price": "req.body.resultados.price",
        "permalink": "req.body.resultados.permalink"
}

###
DELETE http://localhost:3000/605ceb457bb3d00924660e4e

###

PATCH http://localhost:3000/pesquisas/6057dbd67460471cf0ed7503
Content-Type: application/json

{
    "nome": "novo nome"
}