GET http://localhost:3000/pesquisas

###

GET http://localhost:3000/pesquisas/pesquisaML

###

GET http://localhost:3000/pesquisas/6059d931c34d9c4034959f1a

###

POST http://localhost:3000/pesquisas
Content-Type: application/json

{
    "pesquisaFiltro": "q=raspberry",
        "thumbnail": "req.body.resultados.thumbnail",
        "title": "req.body.resultados.title",
        "address_city_name": "req.body.resultados.address_city_name",
        "price": "req.body.resultados.price",
        "permalink": "req.body.resultados.permalink"
}

###
DELETE http://localhost:3000/6059d931c34d9c4034959f1a

###

PATCH http://localhost:3000/pesquisas/6057dbd67460471cf0ed7503
Content-Type: application/json

{
    "nome": "novo nome"
}